[package]
name = "citrust"
version = "0.1.0"
edition = "2024"

[dependencies]
aes = "0.8"
ctr = "0.9"
cipher = "0.4"
clap = { version = "4", features = ["derive"] }
thiserror = "2"
indicatif = "0.17"
