[package]
name = "citrust-cli"
version = "0.2.0"
edition = "2024"

[[bin]]
name = "citrust"
path = "src/main.rs"

[dependencies]
citrust-core = { path = "../citrust-core" }
clap = { version = "4", features = ["derive"] }
indicatif = "0.18"
